[package]
name = "waihona"
version = "0.1.0"
authors = ["Diretnan Domnan <diretnandomnan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.48"
bytes = "1.0"
futures = "0.3"
rusoto_core = "0.46.0"
rusoto_s3 = "0.46.0"
tokio = "1.0"
