name: Publish to Cargo

on:
  push:
    tags: 
      - 'v*'
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{secrets.GCP_CREDENTIALS}}
  AZURE_SECRET_ACCESS_KEY: ${{secrets.AZURE_SECRET_ACCESS_KEY}}


jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run:  echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test crates
        run: |
             sed -i 's/^version.*/version \= "'${RELEASE_VERSION:1}'"/' Cargo.toml
             cargo test -- --nocapture &&
             cargo install cargo-readme &&
             cargo readme > README.md &&
             git config --local user.email "waihona-actions[bot]@users.noreply.bisoncorps.com" &&
             git config --local user.name "waihona-actions[bot]" &&
             git commit -m "Updated version to ${{env.RELEASE_VERSION}}" -a
#             git push
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - name: Push Version To Main
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GH_TOKEN}}
          branch: main
