name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{secrets.GCP_CREDENTIALS}}

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo clippy && cargo build --verbose
      - name: Run tests
        run: cargo test -- --nocapture
